### PR TITLE
Hw1

### PR DESCRIPTION
**Pull request by ayaz91**

### CODE REVIEW

**Comment by powerjg** [comment]
@ayaz91, Could you double check the current merged version for any mistakes?

I also significantly upped the grid sizes. I don't think they had been updated since we were running on the [SPARC T2](https://en.wikipedia.org/wiki/UltraSPARC_T2)

**Comment by powerjg** [comment]
Could you add an assignment to canvas to turn in a pdf of the question answers and a tarball (.tgz) of the code?

Thanks!

**Comment by ayaz91** [comment]
@powerjg I have added the assignment on canvas. Also, I wonder if you intentionally kept the code here: 
https://github.com/jlpteaching/ECS201C/blob/master/HW1/code/omp_ocean.cpp

**Comment by powerjg** [comment]
I definitely didn't! Can you rebase and undo that!

**Pull request merged**
